"""Analytics adapter for agent-patterns ReflectionAgent."""

from __future__ import annotations

from typing import Any, Dict

from agent_patterns.patterns import ReflectionAgent
from langchain_openai import ChatOpenAI
from langgraph.graph import END, StateGraph

from agents.shared.llm_endpoint import normalize_base_url

ANALYTICS_CUSTOM_INSTRUCTIONS = """
You are evaluating data analytics reports (SQL results, tables, insights, charts).

REFLECTION:
- Verify the report answers the user's query with the data shown
- RETRIEVAL queries need data tables; ANALYTICAL queries need analysis beyond raw rows
- Do not penalize reports when workers confirmed missing tables/columns
- Flag placeholder text, generic insights, or missing requested charts

REFINEMENT:
- Improve markdown narrative, structure, and clarity only
- Do NOT invent numbers, rows, or SQL results
- Preserve references to [Table: ...] and [Chart: ...] placeholders exactly
"""


class AnalyticsReflectionAgent(ReflectionAgent):
    """ReflectionAgent that skips Generate (report already built) and supports custom OpenAI endpoints."""

    def __init__(
        self,
        *,
        base_url: str,
        api_key: str,
        model: str,
        max_reflection_cycles: int = 1,
    ):
        self._endpoint_base_url = base_url
        self._endpoint_api_key = api_key or "none"
        self._endpoint_model = model

        llm_configs = {
            "documentation": {
                "provider": "openai",
                "model_name": model,
                "temperature": 0.3,
            },
            "reflection": {
                "provider": "openai",
                "model_name": model,
                "temperature": 0.2,
            },
        }

        super().__init__(
            llm_configs=llm_configs,
            max_reflection_cycles=max_reflection_cycles,
            custom_instructions=ANALYTICS_CUSTOM_INSTRUCTIONS,
        )

    def _get_llm(self, role: str):
        if role in self._llm_cache:
            return self._llm_cache[role]

        if role not in self.llm_configs:
            raise ValueError(f"No configuration found for role '{role}'")

        config = self.llm_configs[role]
        llm = ChatOpenAI(
            model=config["model_name"],
            temperature=config.get("temperature", 0.7),
            max_tokens=config.get("max_tokens", 4000),
            base_url=normalize_base_url(self._endpoint_base_url),
            api_key=self._endpoint_api_key,
        )
        self._llm_cache[role] = llm
        return llm

    def build_graph(self) -> None:
        """Reflect → refine loop; Generate is handled by final_report."""
        workflow = StateGraph(dict)

        workflow.add_node("reflect", self._reflect_on_output)
        workflow.add_node("check_refine", self._check_refinement_needed)
        workflow.add_node("refine", self._refine_output)
        workflow.add_node("check_cycle_limit", self._check_cycle_limit)
        workflow.add_node("final_output", lambda state: state)

        workflow.set_entry_point("reflect")
        workflow.add_edge("reflect", "check_refine")
        workflow.add_conditional_edges(
            "check_refine",
            lambda state: "refine" if state.get("needs_refinement", False) else "done",
            {"refine": "refine", "done": "final_output"},
        )
        workflow.add_edge("refine", "check_cycle_limit")
        workflow.add_conditional_edges(
            "check_cycle_limit",
            lambda state: "continue" if state.get("continue_reflection", False) else "done",
            {"continue": "reflect", "done": "final_output"},
        )
        workflow.add_edge("final_output", END)

        self.graph = workflow.compile()

    def run(self, input_data: str) -> str:
        raise NotImplementedError(
            "Use run_on_report() — analytics reports are generated by final_report first."
        )

    def run_on_report(self, input_task: str, initial_output: str) -> Dict[str, Any]:
        """Run reflect-refine on an existing report."""
        if self.graph is None:
            raise ValueError("Graph has not been built.")

        initial_state = {
            "input_task": input_task,
            "initial_output": initial_output,
            "reflection": None,
            "refined_output": None,
            "needs_refinement": False,
            "final_answer": None,
            "reflection_cycle": 0,
            "max_reflection_cycles": self.max_reflection_cycles,
            "continue_reflection": False,
        }

        self.on_start(input_task)
        try:
            result_state = self.graph.invoke(initial_state)
            final_answer = result_state.get("final_answer")
            if not final_answer:
                final_answer = (
                    result_state.get("refined_output")
                    or result_state.get("initial_output")
                    or initial_output
                )
            result_state["final_answer"] = final_answer
            self.on_finish(final_answer)
            return result_state
        except Exception as exc:
            self.on_error(exc)
            raise


_agent_cache: Dict[str, AnalyticsReflectionAgent] = {}


def get_analytics_reflection_agent(
    *,
    base_url: str,
    api_key: str,
    model: str,
    max_reflection_cycles: int = 1,
) -> AnalyticsReflectionAgent:
    key = f"{base_url}|{api_key}|{model}|{max_reflection_cycles}"
    agent = _agent_cache.get(key)
    if agent is None:
        agent = AnalyticsReflectionAgent(
            base_url=base_url,
            api_key=api_key,
            model=model,
            max_reflection_cycles=max_reflection_cycles,
        )
        _agent_cache[key] = agent
    return agent
